"""Initial migration. 

Revision ID: 61b9dcf73fbd
Revises: 
Create Date: 2020-08-21 14:31:08.496073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b9dcf73fbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblproduct')
    op.add_column('user', sa.Column('address', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'address')
    op.create_table('tblproduct',
    sa.Column('productid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proudctname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('productid', name='tblproduct_pkey')
    )
    # ### end Alembic commands ###
